language: node_js
node_js:
- '0.12'

script:
- make

deploy:
  - provider: s3
    access_key_id: ${AWS_ACCESS}
    secret_access_key: ${AWS_SECRET}
    bucket: editor.openroads-vn.com
    region: ap-southeast-1
    acl: public_read
    local-dir: dist
    skip-cleanup: true
    on:
      branch: master
