language: node_js
node_js:
- '0.12'
env:
  global:
  - GH_REF=github.com/opengovt/openroads-iD.git
  - DEPLOY_BRANCH=master
  - secure: SoZ9/kTuUk3qgcTIfewPL9gCVcsI7KVTHz2pHgvJyf+uECGuAj62bi5uJQxebWlxExI70hS2IG3W4uUQK9OqwTb3+MdzthEDrLiYf13cFLotNT6qUUpqmFPhU2v7msWHmv4SS2lR6oeoFeVtBLLyEMgXZY+KpN+74u1HWuU/Vos=

before_install:
- chmod +x ./.build_scripts/deploy.sh

script:
- make

after_success:
- ./.build_scripts/deploy.sh
